[tox]
envlist = py311,py312,py313,pre-commit

[testenv]
deps =
    pre-commit
    pytest
passenv =
    HOME
    PRE_COMMIT_HOME
commands =
    pytest

[testenv:pre-commit]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure
